第９章
reika-takamiya/java-lesson pull request #10
Opened 2019-05-09 06:50 UTC by reika-takamiya

@shunji-yamaguchi
@hironoriohashi
第９章作成しました。
レビューお願いいたします。

2019-05-09 09:50 UTC, hironoriohashi commented on src/sho9/Heikin2.java
> +        double heikinScore = ((score[0] + score[1] + score[2]) / 3);
この代入だと、平均点の値が正しくないと思います。

2019-05-09 09:51 UTC, hironoriohashi commented on src/sho9/Heikin2.java
> +        double heikinScore = ((score[0] + score[1] + score[2]) / 3);
一度、`score[0]`の点数を62にしてみるとうまくいかなくなると思います。

2019-05-10 00:54 UTC, shunji-yamaguchi requested changes
@reika-takamiya 
レビューしました。ご確認をよろしくお願いします。

2019-05-10 00:54 UTC, shunji-yamaguchi commented on src/sho9/Heikin7.java
> +public class Heikin7 {
@reika-takamiya 
このクラスですがコンパイルが通らないように見えます。（IntelliJから警告がでていませんか？）
修正してみてください。

2019-05-10 00:54 UTC, shunji-yamaguchi commented on src/sho9/Kamoku.java
> +        this.score = tensuu;
@reika-takamiya 
コンストラクの引数名とそれを代入しているクラスのフィールド名が異なっていますが、なにか意図はありますか？
引数の値をそのままフィールドに代入するだけの処理なので、同じ名前にしておくのが良いです。

2019-05-10 00:54 UTC, shunji-yamaguchi commented on src/sho9/Mondai8.java
> +                    int a = data[i];
@reika-takamiya 
変数名が `a` だとなんの意味も伝わってこないのであまり良くないです。
この変数 `a` は一時的に変数の内容を退避させるためのものですね。
そういった場合は `temp` または `tmp` という変数名が一般的に使用されているので、そのようにしておくのが良いと思います。（文化にもよるとおもいますが）

2019-05-10 00:54 UTC, shunji-yamaguchi commented on src/sho9/Mondai9.java
> +    public static void printArray(int[][] a) {
@reika-takamiya 
引数名が `a` だとなんの意味も伝わってこないのであまり良くないですね。
修正してみてください。

2019-05-10 05:16 UTC, reika-takamiya commented on src/sho9/Mondai9.java
> +    public static void printArray(int[][] a) {
@shunji-yamaguchi
引数aに@paramで説明を加えたらいいということですか？

2019-05-10 05:20 UTC, shunji-yamaguchi commented on src/sho9/Mondai9.java
> +    public static void printArray(int[][] a) {
@reika-takamiya 
私なら引数名を`array`にするかなと考えていたのですが、それも良い方法だと思います 👍 
その方法で修正してみてください。

2019-05-10 05:32 UTC, reika-takamiya commented on src/sho9/Mondai9.java
> +    public static void printArray(int[][] a) {
@shunji-yamaguchi
main内でもarrayを使ってるのですが、仮引数でも同じ変数名を使用してもいいのでしょうか？

2019-05-10 06:04 UTC, shunji-yamaguchi commented on src/sho9/Mondai9.java
> +    public static void printArray(int[][] a) {
@reika-takamiya 
> public メソッドの仮引数はちゃんと名前をつけてあげたほうが良いかなー

とのことなのでやはり引数名を修正する方法で直してみてください 🙇 
`publicメソッド`はプロジェクトの別のクラスからも使用できるメソッドなので、命名は特に大事になるということですかね
（`public`については下巻17章で詳しく学ぶみたいです。）

> main内でもarrayを使ってるのですが、仮引数でも同じ変数名を使用してもいいのでしょうか？

mainメソッド内の`array`はmainメソッド内でのみ有効な変数です。
そのため、printArrayメソッドではmainメソッドの`array`を使用することはできません。
逆にいうと、printArrayメソッドでは`array`という名前の変数がないので、メソッドの引数名としても問題ありません。

上巻p142に変数の有効範囲（スコープ）についての説明があります。
list6-7で変数`i`のスコープはmainメソッド内のみになっています。（これが今回でいうmainメソッドの変数`array`ですね）
スコープはmainメソッド内なので、別のメソッドの変数名に`i`を使用しても問題ありません。

スコープについては`{}`で囲まれた内かつ宣言してから後の行、と考えてくれればとりあえず良いと思います。
変数の名前についてはスコープが重複していなければ同じでも問題ありません。（フィールドはまた少し違うのですが、次章以降で学ぶはず。。。）

2019-05-10 06:33 UTC, reika-takamiya commented on src/sho9/Heikin7.java
> +public class Heikin7 {
@shunji-yamaguchi
修正しました。

2019-05-10 06:33 UTC, reika-takamiya commented on src/sho9/Kamoku.java
> +        this.score = tensuu;
@shunji-yamaguchi
引数名とフィールド名を統一しました。

2019-05-10 06:33 UTC, reika-takamiya commented on src/sho9/Heikin2.java
> +        double heikinScore = ((score[0] + score[1] + score[2]) / 3);
@hironoriohashi
修正しました。

2019-05-10 06:34 UTC, reika-takamiya commented on src/sho9/Mondai8.java
> +                    int a = data[i];
@shunji-yamaguchi
変数名をtempにしました。

2019-05-10 06:36 UTC, reika-takamiya commented on src/sho9/Mondai9.java
> +    public static void printArray(int[][] a) {
@shunji-yamaguchi
わかりました！ありがとうございます！
引数名をarrayにしました。

2019-05-10 06:36 UTC, reika-takamiya commented
@shunji-yamaguchi 
@hironoriohashi 
修正しました。
再度レビューお願いいたします！

2019-05-10 08:09 UTC, hironoriohashi commented on src/sho9/Mondai7.java
> +        int maxData = data[0];
変数名`maxData`の`Data`から得られる情報が無いため、
この場合の変数名は`maxNumber`や単に`max`といった変数名が望ましいと思います。

2019-05-10 08:20 UTC, reika-takamiya commented on src/sho9/Mondai7.java
> +        int maxData = data[0];
@hironoriohashi
変数名dataは、dataのままで大丈夫ですか？
numberとかに変更した方がいいですか？

2019-05-10 08:24 UTC, hironoriohashi commented on src/sho9/Mondai7.java
> +        int maxData = data[0];
`data`の方は、意味のある配列に思えなかったので指摘しませんでした。
もし、変更するなら複数の整数を持っていることが分かるように`numbers`や
配列であることを表す`array`といった変数名が良いと思います。

2019-05-10 08:44 UTC, reika-takamiya commented on src/sho9/Mondai7.java
> +        int maxData = data[0];
@hironoriohashi
変数名変更しました。

2019-05-10 10:51 UTC, hironoriohashi approved these changes
良いと思います

2019-05-13 01:15 UTC, shunji-yamaguchi approved these changes
@reika-takamiya 
🆗 です。

2019-05-13 01:27 UTC, merged

2019-05-13 01:29 UTC, reika-takamiya commented
@shunji-yamaguchi 
@hironoriohashi 
ありがとうございます！