第１０章
reika-takamiya/java-lesson pull request #11
Opened 2019-05-10 07:22 UTC by reika-takamiya

@shunji-yamaguchi
@hironoriohashi
第１０章作成しました。
レビューよろしくお願いいたします！

2019-05-10 08:13 UTC, hironoriohashi approved these changes
良いと思います

2019-05-10 08:28 UTC, hironoriohashi requested changes
すいません、Kamoku.javaが無いことを見落としていました。
Kamoku.javaを追加してPRを出してください。

2019-05-10 08:35 UTC, reika-takamiya commented
@hironoriohashi 
すみません。
Kamoku.javaをpushしました。
レビューお願いいたします。

2019-05-10 08:40 UTC, reika-takamiya commented
@hironoriohashi 
Kamoku.java を追加しました。
レビューお願いいたします。

2019-05-10 11:09 UTC, hironoriohashi commented on src/sho10/ProductItem.java
> +        return "[" + "name" + "," + " price" + "]";
この`toString`メソッドでは、`name`や`price`が変わっても出力結果が全て同じものになります。
インスタンスの持つ`name`や`price`が変更されたときに`toString`メソッドの出力結果も変わるようにしてみてください。

2019-05-13 00:46 UTC, reika-takamiya commented on src/sho10/ProductItem.java
> +        return "[" + "name" + "," + " price" + "]";
@hironoriohashi 
コンストラクタを追加しました。

2019-05-13 00:46 UTC, reika-takamiya commented on src/sho10/ProductItem.java
> +        return "[" + "name" + "," + " price" + "]";
@hironoriohashi
コンストラクタを追加しました。

2019-05-13 00:47 UTC, reika-takamiya commented
@shunji-yamaguchi
@hironoriohashi 
修正しました。
再度レビューお願いいたします。

2019-05-13 02:17 UTC, shunji-yamaguchi requested changes
@reika-takamiya 
レビューしました。ご確認をよろしくお願いします。

2019-05-13 02:17 UTC, shunji-yamaguchi commented on src/sho10/Kamoku.java
> +     * @param score 　各科目の点数
@reika-takamiya 
引数名の後の半角スペースは１つにしておきましょう。

また以下のように縦列をそろえる書き方もよいです。
```
 * @param name  科目名
 * @param score 各科目の点数
```

2019-05-13 02:17 UTC, shunji-yamaguchi commented on src/sho10/StudentTest.java
> +
@reika-takamiya 
不要な空行ですね、削除しておいてください。

2019-05-13 05:55 UTC, reika-takamiya commented
@shunji-yamaguchi 
@hironoriohashi 
修正しました。
再度レビューお願いいたします！

2019-05-13 06:30 UTC, shunji-yamaguchi requested changes
@reika-takamiya 
レビューしました。ご確認をよろしくお願いします。

2019-05-13 06:30 UTC, shunji-yamaguchi commented on src/sho10/ProductItem.java
> +        return "[" + "name" + "," + " price" + "]";
@reika-takamiya 

@hironoriohashi さんのこの指摘ですが`toString()`メソッドに修正すべき点がまだありそうです。

2019-05-13 08:14 UTC, reika-takamiya commented
@shunji-yamaguchi 
修正しました。
再度レビューお願いいたします！

2019-05-13 08:30 UTC, shunji-yamaguchi approved these changes
@reika-takamiya 
🆗 です。

2019-05-13 08:51 UTC, merged

2019-05-13 08:51 UTC, reika-takamiya commented
@shunji-yamaguchi 
@hironoriohashi 
ありがとうございます。