第１１章
reika-takamiya/java-lesson pull request #12
Opened 2019-05-15 02:50 UTC by reika-takamiya

@shunji-yamaguchi
@hironoriohashi
第１１章作成しました。
レビューお願いいたします。

2019-05-15 03:39 UTC, hironoriohashi commented on src/sho11/Rectangle21.java
> +            return true;
nullチェックの後の処理を1行で記述できそうです。
1行で記述できるように変更してみてください。

2019-05-15 03:39 UTC, hironoriohashi commented on src/sho11/Rectangle23.java
> +        /* 試し書きなので気にしないでください。
不要なコメント文は削除したい方が良いです

2019-05-15 06:05 UTC, shunji-yamaguchi requested changes
@reika-takamiya 
レビューしました。ご確認をよろしくお願いします。

2019-05-15 06:05 UTC, shunji-yamaguchi commented on src/sho11/Rectangle4.java
> + * コンストラクタの中化からメソッドを呼び出す
@reika-takamiya 
誤字があるので直しておいてください。

2019-05-15 06:05 UTC, shunji-yamaguchi commented on src/sho11/Rectangle23.java
> +        this.height = height;
@reika-takamiya 
教本の範囲外なのですが、[三項演算子](https://www.javadrive.jp/start/ope/index13.html)を使用すると処理がシンプルに記述できます。

2019-05-15 06:05 UTC, shunji-yamaguchi commented on src/sho11/Rectangle24.java
> +        int ey = Math.min(this.y + this.height, rectangle.y + rectangle.height);
@reika-takamiya 
この変数名だと変数がなにを示しているか分かりにくいですね。
修正してみてください。

2019-05-16 01:13 UTC, reika-takamiya commented on src/sho11/Rectangle21.java
> +            return true;
@hironoriohahsi
修正しました。

2019-05-16 01:14 UTC, reika-takamiya commented on src/sho11/Rectangle23.java
> +        /* 試し書きなので気にしないでください。
@hironoriohashi
コメントを削除しました。

2019-05-16 01:14 UTC, reika-takamiya commented on src/sho11/Rectangle4.java
> + * コンストラクタの中化からメソッドを呼び出す
@shunji-yamaguchi
誤字を修正しました。

2019-05-16 01:15 UTC, reika-takamiya commented on src/sho11/Rectangle23.java
> +        this.height = height;
@shunji-yamaguchi
三項演算子を使用して記述しました。

2019-05-16 01:15 UTC, reika-takamiya commented on src/sho11/Rectangle24.java
> +        int ey = Math.min(this.y + this.height, rectangle.y + rectangle.height);
@shunji-yamaguchi
変数名を修正しました。

2019-05-16 01:16 UTC, reika-takamiya commented
@shunji-yamaguchi 
@hironoriohashi 
修正しました。
再度レビューお願いします。

2019-05-17 03:25 UTC, hironoriohashi approved these changes
良いと思います

2019-05-20 00:06 UTC, shunji-yamaguchi approved these changes
@reika-takamiya 
🆗 です。

2019-05-20 01:00 UTC, merged

2019-05-20 01:01 UTC, reika-takamiya commented
@shunji-yamaguchi 
@hironoriohashi 
ありがとうございます！