第１２章
reika-takamiya/java-lesson pull request #13
Opened 2019-05-16 02:09 UTC by reika-takamiya

@hironoriohashi
@shunji-yamaguchi
第１２章作成しました。
レビューお願いいたします。

2019-05-20 03:33 UTC, hironoriohashi approved these changes
良いと思います

2019-05-20 09:00 UTC, shunji-yamaguchi requested changes
@reika-takamiya 
レビューしました。ご確認をよろしくお願いします。

2019-05-20 09:00 UTC, shunji-yamaguchi commented on src/sho12/PlacedRectangle.java
> +//import sho10.Rectangle;
@reika-takamiya 
不要なコメントですね、削除しておきましょう。

2019-05-21 01:22 UTC, reika-takamiya commented on src/sho12/PlacedRectangle.java
> +//import sho10.Rectangle;
@shunji-yamaguchi
不要なコメントを削除しました。

2019-05-21 01:22 UTC, reika-takamiya commented
@shunji-yamaguchi 
再度レビューお願いします。

2019-05-21 01:23 UTC, shunji-yamaguchi approved these changes
@reika-takamiya 
🆗 です。

2019-05-21 02:10 UTC, merged