第16章
reika-takamiya/java-lesson pull request #17
Opened 2019-05-27 01:52 UTC by reika-takamiya

@shunji-yamaguchi
@hironoriohashi
第16章作成しました。
レビューお願いします。

2019-05-27 09:52 UTC, hironoriohashi approved these changes
良いと思います

2019-05-27 10:28 UTC, shunji-yamaguchi requested changes
@reika-takamiya 
レビューしました。ご確認をよろしくお願いします。

2019-05-27 10:28 UTC, shunji-yamaguchi commented on src/sho16/Runner.java
> +    }
@reika-takamiya 
サンプルコードに実行のための処理を追加で書けているのはとても良いです 👍 
しかし、ここでスレッドを終了させるためのメソッド`stopRunning()`を呼び出すと、自分で自分のスレッドを終了することになります。
自身以外のスレッドが終了する形に修正してみてください。

2019-05-27 10:28 UTC, shunji-yamaguchi commented on src/sho16/Periodic.java
> +                Thread.sleep(time);
@reika-takamiya 
余談ですが、`i`秒スリープしたい場合は`TimeUnit`を使用して、`TimeUnit.SECONDS.sleep(i);`と書くこともできるそうです。
ミリ秒に直す計算が不要なので便利ですね。

2019-05-29 02:05 UTC, reika-takamiya commented on src/sho16/Runner.java
> +    }
@shunji-yamaguchi
修正しました。

2019-05-29 02:06 UTC, reika-takamiya commented
@shunji-yamaguchi
修正しました。
再度レビューお願いします。

2019-05-29 02:09 UTC, shunji-yamaguchi approved these changes
@reika-takamiya 
🆗 です 👍

2019-05-29 02:12 UTC, merged

2019-05-29 02:12 UTC, reika-takamiya commented
@shunji-yamaguchi
@hironoriohashi
ありがとうございます