第17章
reika-takamiya/java-lesson pull request #18
Opened 2019-05-27 06:05 UTC by reika-takamiya

@shunji-yamaguchi
@hironoriohashi
第17章作成しました。
レビューお願いします。

2019-05-27 09:56 UTC, hironoriohashi approved these changes
良いと思います

2019-05-28 00:21 UTC, shunji-yamaguchi approved these changes
@reika-takamiya 
🆗 です。
１点コメントしましたが、問題なければマージで良いと思います。

2019-05-28 00:21 UTC, shunji-yamaguchi commented on src/sho17/Hello.java
> + */
@reika-takamiya 
今回のコードはクラスのコメントがimport文より上にありますが、わざとでしょうか？
この書き方だとクラスのドキュメンテーションコメントとしては認識されません。
import文が重要なコードのため、あえてこうしたのでしたらこのままでも良いと思います 🙆‍♂

2019-05-28 08:29 UTC, reika-takamiya commented on src/sho17/Hello.java
> + */
@shunji-yamaguchi
コメントの位置を修正しました。

2019-05-28 08:29 UTC, reika-takamiya commented
@shunji-yamaguchi 
修正しました。
再度レビューお願いします。

2019-05-28 09:24 UTC, shunji-yamaguchi requested changes
@reika-takamiya 
`Hello.java`についてはokです。
`Math2.java` `Max.java`のコメントについても同様の修正をお願いします。

2019-05-29 00:51 UTC, reika-takamiya commented
@shunji-yamaguchi 
コメントを修正しました。
再度レビューお願いします。

2019-05-29 00:52 UTC, shunji-yamaguchi approved these changes
@reika-takamiya 
🆗 です。

2019-05-29 02:12 UTC, merged