第18章
reika-takamiya/java-lesson pull request #19
Opened 2019-05-29 06:53 UTC by reika-takamiya

@shunji-yamaguchi
@hironoriohashi
第18章作成しました。
レビューお願いします。

問題18‐2で、`FileReade`を使うと文字化けしたので`FileInputStream`を使用しました。

2019-05-30 07:06 UTC, shunji-yamaguchi requested changes
@reika-takamiya 
レビューしました。ご確認をよろしくお願いします。

2019-05-30 07:06 UTC, shunji-yamaguchi commented on src/sho18/ShowFile1.java
> +        try (BufferedReader reader = new BufferedReader(new FileReader(filename))) {
👍

2019-05-30 07:06 UTC, shunji-yamaguchi commented on src/sho18/WriteFile1.java
> +             PrintWriter writer = new PrintWriter(new BufferedWriter(new FileWriter(filename)))) {
@reika-takamiya 
`BufferedReader`に縦をそろえてくれていますが、4タブのインデントからは外れてしまっています。
インデントは統一するようにしてください。
またこの場合は後続の処理との区別がつくように、２つ分のインデントを入れておくのがよいです。

2019-05-30 07:06 UTC, shunji-yamaguchi commented on src/sho18/FileDump1.java
> +        }
@kenta-yamazaki
このif文による処理ですが、`String.format()`を使用するとif文なしで書くことができます。
`String.format()`を使用して書いてみてください 🙏

2019-05-30 07:06 UTC, shunji-yamaguchi commented on src/sho18/FindFile.java
> +            reader.close();
@reika-takamiya 
closeメソッドを使用する場合はfinally句に記述するのが良いです。
途中で例外が投げられた場合も確実にcloseを実行するためです。

2019-05-30 07:06 UTC, shunji-yamaguchi commented on src/sho18/FindFile.java
> +            while ((line = reader.readLine()) != null) {
@reika-takamiya 
`lineNumber`の処理は、for文を使用して書くこともできそうです。
while文でなくfor文を使用する形に直してみてください 🙏

2019-05-30 07:06 UTC, shunji-yamaguchi commented on src/sho18/Prime.java
> +    static final int MAX_PRIME = 1000;
@reika-takamiya 
この定数はこのクラスでしか使用しないものですね。
変数のスコープは最小にしておくのが良いので、privateにしておきましょう。

2019-05-30 07:06 UTC, shunji-yamaguchi commented on src/sho18/Prime.java
> +    public static void writePrime(PrintWriter writer) {
@reika-takamiya 
このメソッドはこのクラスからのみ呼び出されるメソッドですね。
外部のクラスに公開する必要性はないので、privateにしておきましょう。

2019-05-31 01:59 UTC, reika-takamiya commented on src/sho18/FileDump1.java
> +        }
@shunji-yamaguchi
String.format()を使用しました。

2019-05-31 02:00 UTC, reika-takamiya commented on src/sho18/FindFile.java
> +            reader.close();
@shunji-yamaguchi
try-with-resource文に修正しました。

2019-05-31 02:00 UTC, reika-takamiya commented on src/sho18/FindFile.java
> +            while ((line = reader.readLine()) != null) {
@shunji-yamaguchi
for文を使用する形に修正しました。

2019-05-31 02:00 UTC, reika-takamiya commented on src/sho18/Prime.java
> +    static final int MAX_PRIME = 1000;
@shunji-yamaguchi
スコープを修正しました。

2019-05-31 02:01 UTC, reika-takamiya commented
@shunji-yamaguchi 
修正しました。
再度レビューお願いします。

2019-05-31 04:45 UTC, shunji-yamaguchi approved these changes
@reika-takamiya 
🆗 です 🎉

2019-05-31 04:45 UTC, shunji-yamaguchi commented on src/sho18/WriteFile1.java
> +             PrintWriter writer = new PrintWriter(new BufferedWriter(new FileWriter(filename)))) {
IntelJフォーマットでこのように修正されるようなので、okとします 🙏

2019-05-31 04:45 UTC, shunji-yamaguchi commented on src/sho18/WriteFile1.java
> +        try (BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
@reika-takamiya 
補足です。
closeメソッドについてですが、基本的に内部のラップされたストリームも自動でcloseされます。
なのでこの場合`reader.close()`を実行すると`new InputStreamReader`と`System.in`についてもcloseが実行されます。
通常のストリームなら必要なときにまたインスタンスを生成すれば良いですが、`System.in`についてはSystemクラスのクラスフィールドなので、一度closeしてしまうと再度使用することはできません。
`System.in`を使用する際は注意が必要です。

2019-06-04 09:20 UTC, hironoriohashi approved these changes
良いと思います

2019-06-04 23:55 UTC, reika-takamiya commented
@shunji-yamaguchi 
@hironoriohashi 
ありがとうございました 🙇‍♀

2019-06-04 23:55 UTC, merged