第1章
reika-takamiya/java-lesson pull request #2
Opened 2019-04-22 06:45 UTC by reika-takamiya

@shunji-yamaguchi 
@hironoriohashi

第一章あげました。
レビューお願いします。

2019-04-22 06:52 UTC, hironoriohashi commented on src/sho_0/Hello.java
> +package sho_0;
これは0章の課題ではないでしょうか？

2019-04-22 08:01 UTC, reika-takamiya commented on src/sho_0/Hello.java
> +package sho_0;
@hironoriohashi
sho0の途中からsho1のブランチを切ってしまったためsho0の課題が差分として発生しています。そのため最新masterをmergeして解決しました。

2019-04-22 08:34 UTC, shunji-yamaguchi requested changes
@reika-takamiya 
レビューしました。ご確認をよろしくお願いします。

2019-04-22 08:34 UTC, shunji-yamaguchi commented on src/sho1/Aisatsu.java
> +    public static void main (String[] args) {
@reika-takamiya 
`main`の後の半角スペースはなしで統一していただきたいです。`Aisatsu2.java` `Hello.java`についても同様にお願いします。

2019-04-22 08:34 UTC, shunji-yamaguchi commented on src/sho1/Aisatsu2.java
> + *Aisatsu.javaを修正してSystem.out.printlnを一度だけ使用して同じ結果にする
@reika-takamiya 
細かいですが、`*`の後に半角スペースが欲しいですね。

2019-04-22 08:34 UTC, shunji-yamaguchi commented on src/sho1/Kantan.java
> + * 意外にjavaって簡単だ。と表示して終了するプログラム
@reika-takamiya 
コメントの内容と実際に表示される内容が異なっていませんか？正しいほうに修正をお願いします。

2019-04-22 08:34 UTC, shunji-yamaguchi commented on src/sho1/Hello.java
> +画面にHello!と表示して終了するプログラム
@reika-takamiya 
こちらもJavaDocのフォーマットにしたがって修正お願いします。

2019-04-22 08:34 UTC, shunji-yamaguchi commented on src/sho1/Aisatsu2.java
> +        System.out.println("おはよう。\nこんにちは。\nこんばんは。");
@reika-takamiya 
`Aisatsu.java`とは改行コードについて出力が異なっていそうです。

2019-04-22 08:34 UTC, shunji-yamaguchi commented on src/sho1/Kantan.java
> +
@reika-takamiya 
この空行は違和感がありますね。削除するのが良いと思います。

2019-04-22 09:03 UTC, reika-takamiya commented on src/sho1/Aisatsu.java
> +    public static void main (String[] args) {
main後の半角スペース削除しました

2019-04-22 09:03 UTC, reika-takamiya commented on src/sho1/Aisatsu.java
> +    public static void main (String[] args) {
main後の半角スペース削除しました。

2019-04-22 09:03 UTC, reika-takamiya commented on src/sho1/Aisatsu2.java
> + *Aisatsu.javaを修正してSystem.out.printlnを一度だけ使用して同じ結果にする
*後に半角スペース追加しました。

2019-04-22 09:03 UTC, reika-takamiya commented on src/sho1/Aisatsu2.java
> +        System.out.println("おはよう。\nこんにちは。\nこんばんは。");
Aisatsu.javaと同じ改行に変更しました。

2019-04-22 09:04 UTC, reika-takamiya commented on src/sho1/Hello.java
> +画面にHello!と表示して終了するプログラム
しゅうせいしました。

2019-04-22 09:04 UTC, reika-takamiya commented on src/sho1/Kantan.java
> + * 意外にjavaって簡単だ。と表示して終了するプログラム
正しいほうに修正しました。

2019-04-22 09:04 UTC, reika-takamiya commented on src/sho1/Kantan.java
> +
空行削除しました。

2019-04-22 09:06 UTC, reika-takamiya commented
@hironoriohashi 
@shunji-yamaguchi 
修正したので再度レビューお願いします。

2019-04-22 10:20 UTC, shunji-yamaguchi requested changes
@reika-takamiya 
レビューしました。ご確認をよろしくお願いします。

2019-04-22 10:20 UTC, shunji-yamaguchi commented on src/sho1/Aisatsu2.java
> +        System.out.println("おはよう。\nこんにちは。\nこんばんは。");
@reika-takamiya 
修正漏れていませんか？前回とコードが変わっていなさそうです。

2019-04-22 10:20 UTC, shunji-yamaguchi commented on src/Calc1.java
> +package PACKAGE_NAME;
@reika-takamiya 
関係ないクラスがコミットされてしまっていますね。

- 現在のブランチと関係ない作業は行わないよう注意してください。
- ブランチを切り替える際に未コミットの変更がありかつ変更先のブランチとコンフリクトしない場合は、変更内容を維持したままブランチの切り替えに成功します。そのためブランチを切り替える際は変更内容をコミットまたはスタッシュで退避するよう気をつけてください。
- push前はコミットの変更内容を確認してから行うのがよいです。

2019-04-22 10:20 UTC, shunji-yamaguchi commented on src/sho1/Hello.java
> +}
@reika-takamiya 
ファイル最後は改行をお願いします。
kunouさんが紹介してくださっていた https://qiita.com/tanakahisateru/items/66359b6217e7ac728856 やっておくと良いと思いますよ。

2019-04-22 10:20 UTC, shunji-yamaguchi commented on src/sho1/Kantan.java
> + * 意外に"java"って簡単だ。と表示して終了するプログラム
@reika-takamiya 
`意外に"java"って簡単だ。`の出力は改行ありで3回ですね。
それがわかるようコメントも修正をお願いします。

2019-04-23 00:33 UTC, shunji-yamaguchi commented on src/sho1/Aisatsu2.java
> +        System.out.println("おはよう。\nこんにちは。\nこんばんは。");
@reika-takamiya 
すいません。こちら私の指摘が誤っています。
最後に改行コードがないと勘違いしていました。
指摘は取り下げます 🙇

2019-04-23 00:47 UTC, reika-takamiya commented on src/sho1/Kantan.java
> + * 意外に"java"って簡単だ。と表示して終了するプログラム
@shunji-yamaguchi
コメントを修正しました。

2019-04-23 00:47 UTC, reika-takamiya commented on src/sho1/Hello.java
> +}
@shunji-yamaguchi
改行しました。kunouさんに紹介していただいた設定も行いました。

2019-04-23 01:31 UTC, reika-takamiya commented
@shunji-yamaguchi 
@hironoriohashi 
修正しました。
再度レビューお願いします。

2019-04-23 01:37 UTC, shunji-yamaguchi approved these changes
@reika-takamiya 
🆗 です。

2019-04-23 03:15 UTC, hironoriohashi approved these changes
良いと思います

2019-04-23 04:27 UTC, merged