第4章
reika-takamiya/java-lesson pull request #5
Opened 2019-04-24 05:30 UTC by reika-takamiya

@shunji-yamaguchi
@hironoriohashi
第4章作成しました。
レビューお願いします。

2019-04-24 06:29 UTC, shunji-yamaguchi requested changes
@reika-takamiya 
レビューしました。ご確認をよろしくお願いします。

2019-04-24 06:29 UTC, shunji-yamaguchi commented on src/sho4/Kasa1.java
> +        public static void main(String[] args) {
@reika-takamiya 
インデントがずれていますね。

2019-04-24 06:29 UTC, shunji-yamaguchi commented on src/sho4/Kasa2.java
> +              if (n > 100) {
@reika-takamiya 
ここのif文についても、インデントがずれていますね。

2019-04-24 06:29 UTC, shunji-yamaguchi commented on src/sho4/Kasa1.java
> +                    }
@reika-takamiya 
ここからもインデントがずれていますね。

2019-04-24 06:29 UTC, shunji-yamaguchi commented on src/sho4/Kasa3.java
> +;
@reika-takamiya 
不要なセミコロンです。

2019-04-24 06:29 UTC, shunji-yamaguchi commented on src/sho4/Mondai3.java
> +            if (0 <= n && n <= 11) {
👍

2019-04-24 06:29 UTC, shunji-yamaguchi commented on src/sho4/Mondai3.java
> +            int n = Integer.parseInt(line);
@reika-takamiya 
こちらの変数ですが、時刻であることが分かるような名前に修正してみてください。
小さいコードでも何の変数なのか分かる名前を付けるようにするのが良いです。

2019-04-24 06:49 UTC, reika-takamiya commented
@shunji-yamaguchi 
@hiranoriohashi
修正しました。
再レビューお願いいたします。

2019-04-24 06:57 UTC, shunji-yamaguchi approved these changes
@reika-takamiya 
🆗 です。

2019-04-24 12:31 UTC, hironoriohashi commented on src/sho4/Kasa1.java
> +            int n = Integer.parseInt(line);
> こちらの変数ですが、時刻であることが分かるような名前に修正してみてください。
小さいコードでも何の変数なのか分かる名前を付けるようにするのが良いです。

こちらの変数も降水確率を格納していることが分かるように修正してみてください。

2019-04-25 00:10 UTC, reika-takamiya commented
@hironoriohashi 
変数名修正しました。
再度レビューお願いします。

2019-04-25 01:04 UTC, hironoriohashi commented on src/sho4/Kasa1.java
> +            int rainyPercent = Integer.parseInt(line);
良いと思います。
他に分かりにくい変数名になっている箇所は無いでしょうか？

2019-04-25 02:31 UTC, reika-takamiya commented
@hironoriohashi 
Kasa2.javaと、Kasa3.javaの変数名も修正しました。
再度レビューお願いいたします。

2019-04-25 03:05 UTC, hironoriohashi approved these changes
良いと思います

2019-04-25 03:58 UTC, reika-takamiya commented
@shunji-yamaguchi 
@hironoriohashi 
ありがとうございます！

2019-04-25 03:58 UTC, merged