第5章
reika-takamiya/java-lesson pull request #6
Opened 2019-04-25 02:26 UTC by reika-takamiya

@shunji-yamaguchi
@hiranoriohashi

第5章作成しました。
レビューお願いします。

2019-04-25 04:33 UTC, shunji-yamaguchi requested changes
@reika-takamiya 
レビューしました。ご確認をよろしくお願いします。

2019-04-25 04:33 UTC, shunji-yamaguchi commented on src/sho5/Drink3.java
> +        } catch (NumberFormatException e) {
@reika-takamiya 
ここで`NumberFormatException`をcatchしていますが、サンプルコードにはない処理ですね。削除しておいてください。

どういうときに必要なのかは下巻13章で学習する内容なので、無理に理解しなくても大丈夫です。
気になれば下巻13章p86に`NumberFormatException`について記述があるので読んでみてもよいですよ。

2019-04-25 04:33 UTC, shunji-yamaguchi commented on src/sho5/Mondai5.java
> +            catch(IOException e) {
@reika-takamiya 
インデントがずれていますね 👀

2019-04-25 04:33 UTC, shunji-yamaguchi commented on src/sho5/Mondai5.java
> + * <pre>{@code
👍

2019-04-25 04:33 UTC, shunji-yamaguchi commented on src/sho5/Mondai5.java
> +            } catch(NumberFormatException e) {
@reika-takamiya 
このコードも`NumberFormatException`のcatchが不要なコードなので削除しておいてください 🙏

2019-04-25 04:33 UTC, shunji-yamaguchi commented on src/sho5/Drink2.java
> +public class Drink2 {
@reika-takamiya 
せっかくなのでp125問題5-8のエラーを解決できるようなプログラムも作成してみてください。
このクラスを直接修正していただいても良いです。

2019-04-25 04:33 UTC, shunji-yamaguchi commented on src/sho5/Mondai7.java
> +            int number = Integer.parseInt(line);
@reika-takamiya 
こちら全角数字を入力するよう求める文章となっています。
教本の問題文とあってるでしょうか？

2019-04-25 07:25 UTC, reika-takamiya commented on src/sho5/Drink3.java
> +        } catch (NumberFormatException e) {
@shunji-yamaguchi
削除しました。

2019-04-25 07:25 UTC, reika-takamiya commented on src/sho5/Mondai5.java
> +            } catch(NumberFormatException e) {
@shunji-yamaguchi
削除と、インデントを修正しました。

2019-04-25 07:25 UTC, reika-takamiya commented on src/sho5/Drink2.java
> +public class Drink2 {
@shunji-yamaguchi
問題5-8作成しました。

2019-04-25 07:26 UTC, reika-takamiya commented on src/sho5/Mondai7.java
> +            int number = Integer.parseInt(line);
@shunji-yamaguchi
文章修正しました。

2019-04-25 07:26 UTC, reika-takamiya commented on src/sho5/Mondai7.java
> +            int number = Integer.parseInt(line);
@shunji-yamaguchi
文章修正しました。

2019-04-25 07:26 UTC, reika-takamiya commented
@shunji-yamaguchi 
@hironoriohashi
修正しました。
再度レビューお願いします。

2019-04-25 15:23 UTC, hironoriohashi commented on src/sho5/Drink1.java
> +            int number = Integer.parseInt(line);
変数名が`number`や`moji`では抽象的なので、
変数に格納されている値がユーザの選択だと分かるような変数名にしてみてください。

2019-04-26 00:11 UTC, shunji-yamaguchi requested changes
@reika-takamiya 
新しいコミットがないですね。プッシュを忘れていませんか？

2019-04-26 02:19 UTC, reika-takamiya commented
@shunji-yamaguchi 
@hironoriohashi 　
再度編集してpushしなおしました。
rejectされたので、force pushしたのですが大丈夫でしょうか・・？

2019-04-26 03:26 UTC, hironoriohashi commented on src/sho5/Drink1.java
> +            int userNoSelection = Integer.parseInt(line);
`userNoSelection`のNoはNumberの略でしょうか？
もし、そうであれば否定のNoと混同しないように省略せず`userNumberSelection`とした方が良いです。

`line`には変数名に型の情報が入っていませんし、
型の情報も除いて`userSelection`としても良いかもしれません。

2019-04-26 04:38 UTC, shunji-yamaguchi approved these changes
@reika-takamiya 
🆗 です。

force push は問答無用でリモートの内容を上書きしてしまうので、なにが起こるのか把握できていない場合は行わないよう注意してください。
今回は問題なさそうです。

2019-04-26 04:38 UTC, shunji-yamaguchi commented on src/sho5/Mondai7.java
> +            int userNoSelection = Integer.parseInt(line);
@reika-takamiya 
ちなみに`Integer.parseInt()`がint型に変換できる形式は半角数字以外にもあり、全角数字を渡しても問題なくint型に変換してくれます。
今回は教本の問題文に合わせて修正していただきましたが、全角文字の入力を促す内容でもエラーにはならないです。

2019-04-26 07:55 UTC, reika-takamiya commented
@hironoriohahshi 
@shunji-yamaguchi 
変数名を修正しました。
再度レビューお願いします。

2019-04-26 07:56 UTC, reika-takamiya commented on src/sho5/Drink1.java
> +            int userNoSelection = Integer.parseInt(line);
@hironoriohashi
変数名編集しました。
慣れるまでとても難しいです・・

2019-04-26 13:23 UTC, hironoriohashi approved these changes
良いと思います

2019-05-08 02:14 UTC, merged