第6章
reika-takamiya/java-lesson pull request #7
Opened 2019-04-25 05:31 UTC by reika-takamiya

@shunji-yamaguchi
@hironoriohashi
第6章作成しました。
レビューお願いします。

2019-04-25 06:39 UTC, shunji-yamaguchi requested changes
@reika-takamiya 
レビューしました。ご確認をよろしくお願いします

2019-04-25 06:39 UTC, shunji-yamaguchi commented on src/sho6/DrawGraph.java
> +            System.out.println("");
@reika-takamiya 
このコードだと教本の実行結果とは異なる結果となりますね。

2019-04-25 06:39 UTC, shunji-yamaguchi commented on src/sho6/Mondai2.java
> +            System.out.println("");
@reika-takamiya 
問題6-2で指定されたグラフとは異なる結果になりますね。
修正してください。

2019-04-25 06:39 UTC, shunji-yamaguchi commented on src/sho6/Mondai4.java
> +            System.out.println("");
@reika-takamiya 
問題6-4で指定された九九の表とは異なる結果となりますね。
修正してください。

2019-04-25 06:39 UTC, shunji-yamaguchi commented on src/sho6/Count3.java
> +            System.out.println("3乗は" + (number * number * number) + "です。");
@reika-takamiya 
累乗は[Math.pow](https://docs.oracle.com/javase/jp/8/docs/api/java/lang/Math.html#pow-double-double-) を使って求めることができます。

2019-04-25 06:39 UTC, shunji-yamaguchi commented on src/sho6/Count2.java
> +        for (int number = 0; number < 3; number++) {
@reika-takamiya 
for文で使用するカウンタの変数名ですが教本のように `i` `j` `k` ... と使用していくのが慣例です。
これが慣例となっているので、for文のカウンタの変数名は悩む必要がなく、2重ループでも `i` や `k` が何重ループ目のカウンタ変数なのか推測できます。

2019-04-26 01:27 UTC, reika-takamiya commented on src/sho6/DrawGraph.java
> +            System.out.println("");
@shunji-yamaguchi
正しい実行結果になるように修正しました。

2019-04-26 01:28 UTC, reika-takamiya commented on src/sho6/Mondai2.java
> +            System.out.println("");
@shunji-yamaguchi
正しい実行結果になるように修正しました。

2019-04-26 01:28 UTC, reika-takamiya commented on src/sho6/Mondai4.java
> +            System.out.println("");
@shunji-yamaguchi
正しい実行結果になるように修正しました。
変数名修正しました。

2019-04-26 01:29 UTC, reika-takamiya commented on src/sho6/Count3.java
> +            System.out.println("3乗は" + (number * number * number) + "です。");
@shunji-yamaguchi
Math.powの使い方、あってますか・・・？
変数名の付け方もあってるかわかりません・・・。

2019-04-26 01:32 UTC, reika-takamiya commented on src/sho6/Count2.java
> +        for (int number = 0; number < 3; number++) {
@shunji-yamaguchi
変数名変更しました。
どういった場合にi,j,kなどを使うのか教えてください。

2019-04-26 01:33 UTC, reika-takamiya commented
@shunji-yamaguchi 
@hironoriohashi
修正しました。
再度レビューお願いします。

2019-04-26 03:32 UTC, hironoriohashi commented on src/sho6/Count3.java
> +            double resultOfPower2 = Math.pow(i, 3);
`resultOfPower1`と`resultOfPower2`では、乗算した結果が入っていると想像できても2乗した結果と3乗した結果と想像できないです。
2乗した結果と3乗した結果だと分かるような変数名にしてみてください。

2019-04-26 05:13 UTC, shunji-yamaguchi requested changes
@reika-takamiya 
レビューしました。ご確認をよろしくお願いします。

2019-04-26 05:13 UTC, shunji-yamaguchi commented on src/sho6/Count3.java
> +            System.out.println("3乗は" + resultOfPower2 + "です。");
@reika-takamiya 
こちら教本の実行結果とはことなっていますね。
教本の実行結果や問題文の内容を確実に満たすよう、注意しましょう。

`Math.pow()`の使い方については 🆗 です。
変数名については大橋さんの指摘を参考にしてみてください 🙏

2019-04-26 05:13 UTC, shunji-yamaguchi commented on src/sho6/DrawGraph.java
> +            System.out.println("");
@reika-takamiya 
こちらもまだ異なる部分がありそうです。
修正後は実行して確認するよう心掛けてください。

2019-04-26 05:13 UTC, shunji-yamaguchi commented on src/sho6/Mondai2.java
> +            System.out.println("");
@reika-takamiya 
こちらも修正すべき点がまだありそうです。

2019-04-26 05:13 UTC, shunji-yamaguchi commented on src/sho6/Mondai4.java
> +            System.out.println("");
@reika-takamiya 
こちらも修正すべき点がまだありそうです。

2019-04-26 05:39 UTC, reika-takamiya commented on src/sho6/Count3.java
> +            double resultOfPower2 = Math.pow(i, 3);
@hironoriohashi
調べたところ、
2乗→squareResult
3乗→cubeResult　と出てきたのですが、どうでしょうか・・・？

2019-04-26 05:40 UTC, shunji-yamaguchi commented on src/sho6/Count2.java
> +        for (int number = 0; number < 3; number++) {
@reika-takamiya 

私の場合はfor文を使う場合は、ほぼ `i` を使用しています。
2重目のループでは `j` 、3重目のループでは `k` を使用しますが、なるべく多重ループ文は書かないよう心がけてます（読みずらいので）。

ただ[久納さんや酒井さんのいうとおりいろいろなパターンがあるみたい](https://idobata.io/archives/messages/30593712#message_30593712)なので、確実な決まりはありません。
難しければとりあえずfor文では `i`  `j` を使用すればいいかなと思います。
プログラムに慣れてくれば、ケースバイケースで自分で考えれるようになると思うので。

2019-04-26 08:22 UTC, reika-takamiya commented
@shunji-yamaguchi 
@hironoriohashi 
修正しました。
教本をもっとしっかり見て作成します・・・。
再度レビューお願いします。

2019-04-26 08:41 UTC, shunji-yamaguchi commented
@reika-takamiya 
修正コミットがプッシュされてなさそうですね。お願いします 🙏

2019-04-26 08:46 UTC, reika-takamiya commented
@shunji-yamaguchi 
pushしました
何度もごめんなさい！
お願いします！

2019-04-26 08:53 UTC, shunji-yamaguchi approved these changes
@reika-takamiya 
🆗 です 🙆‍♂️

2019-04-26 13:27 UTC, hironoriohashi approved these changes
良いと思います

2019-05-06 23:59 UTC, merged