第８章
reika-takamiya/java-lesson pull request #9
Opened 2019-05-08 01:37 UTC by reika-takamiya

@shunji-yamaguchi
@hironoriohashi
第８章作成しました。
レビューお願いいたします。

2019-05-08 04:00 UTC, hironoriohashi commented on src/sho8/Discount2.java
> +    public static int halve(int n) {
好みの問題ですが、クラス内でメソッドを連続して記述するときは1行の空行を入れた方が良いです。
山口さんに連携して頂いた[コーディング規約](https://kazurof.github.io/GoogleJavaStyle-ja/#s4-6-whitespace)にもそう書いてあります。

2019-05-09 01:01 UTC, shunji-yamaguchi requested changes
@reika-takamiya 
レビューしました。ご確認をよろしくお願いします。

2019-05-09 01:01 UTC, shunji-yamaguchi commented on src/sho8/Mondai2.java
> +        System.out.println("");
@reika-takamiya 
改行コードのみの出力なら引数なしの`println`を使用しておきましょう。

2019-05-09 01:01 UTC, shunji-yamaguchi commented on src/sho8/Mondai2.java
> +        for (i = 0; i < squareResult; i++) {
@reika-takamiya 
変数 `i` はfor文の内部でのみ使用する変数なので、for文の外で宣言する意味はなさそうですね。変数のスコープは最小にすべきなので修正しておいてください。

2019-05-09 01:01 UTC, shunji-yamaguchi commented on src/sho8/Power1.java
> +    /*xのn乗の計算*/
@reika-takamiya 
こちらサンプルコードの通りのコメントなので問題ないのですが、せっかくなのでJavaDco形式で書いてみてください。

[ここの「メソッドのコメント」欄に書き方が載っています](https://qiita.com/maku77/items/6410c67ce95e08d8d1bd#%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89%E3%81%AE%E3%82%B3%E3%83%A1%E3%83%B3%E3%83%88)
難しければ以下を参考に書いてみてください。

````
/**
 * {ここにメソッドの説明を書く}
 *
 * @param number {ここに引数numberについての説明を書く}
 * @param square {ここに引数squareについての説明を書く}
 * @return {ここに戻り値についての説明を書く}
 */
public static int getPower(int number, int square) {
````
コメントは数文字程度の簡潔なもので大丈夫です（このメソッドはシグネチャから十分使い方が伝わるので）

2019-05-10 00:03 UTC, reika-takamiya commented on src/sho8/Discount2.java
> +    public static int halve(int n) {
@hironoriohashi
空行を追加しました。

2019-05-10 00:03 UTC, reika-takamiya commented on src/sho8/Mondai2.java
> +        System.out.println("");
@shunji-yamaguchi
改行コードを修正しました。

2019-05-10 00:04 UTC, reika-takamiya commented on src/sho8/Mondai2.java
> +        for (i = 0; i < squareResult; i++) {
@shunji-yamaguchi
for文を修正しました。

2019-05-10 00:04 UTC, reika-takamiya commented on src/sho8/Power1.java
> +    /*xのn乗の計算*/
@shunji-yamaguchi
コメントの書き方を修正しました。

2019-05-10 00:05 UTC, reika-takamiya commented
@shunji-yamaguchi 
@hironoriohashi 
修正しました。
再度レビューお願いいたします。

2019-05-10 00:59 UTC, shunji-yamaguchi approved these changes
@reika-takamiya 
🆗 です。

2019-05-10 03:02 UTC, hironoriohashi approved these changes
良いと思います

2019-05-10 04:41 UTC, merged